'use client';

import { useMutation } from '@tanstack/react-query';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { ConfirmDialog } from '../../../../components/confirm-dialog';
import { Icon } from '../../../../components/icons';
import { DifficultyBadge, ErrorBox, Loading, ProgressBar } from '../../../../components/ui';
import { api } from '../../../../lib/api';
import { Difficulty } from '../../../../types';

type Start = { attemptId: string; test: { id: string; title: string; difficulty: Difficulty; durationMinutes?: number }; questions: { id: string; text: string; order: number; points: number; options: { id: string; text: string; order: number }[] }[] };
type Result = { attemptId: string; totalQuestions: number; correctAnswers: number; wrongAnswers: number; score: number; percentage: number; currentDifficulty: Difficulty; recommendedDifficulty: Difficulty; recommendation: string };

export default function TestRunner() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const started = useRef(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [start, setStart] = useState<Start | null>(null); const [error, setError] = useState(''); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string, string>>({}); const [left, setLeft] = useState<number | null>(null);
  useEffect(() => { if (started.current) return; started.current = true; api<Start>(`/tests/${id}/start`, { method: 'POST' }).then(result => { setStart(result); setLeft((result.test.durationMinutes ?? 0) * 60 || null); }).catch(caught => setError(caught.message)); }, [id]);
  useEffect(() => { if (left === null || left <= 0) return; const timer = setInterval(() => setLeft(value => Math.max(0, (value ?? 1) - 1)), 1000); return () => clearInterval(timer); }, [left]);
  const submit = useMutation({ mutationFn: () => api<Result>(`/attempts/${start!.attemptId}/submit`, { method: 'POST', body: JSON.stringify({ answers: Object.entries(answers).map(([questionId, selectedOptionId]) => ({ questionId, selectedOptionId })) }) }), onSuccess: result => { sessionStorage.setItem(`result:${result.attemptId}`, JSON.stringify(result)); router.push(`/attempts/${result.attemptId}/result`); }, onError: caught => setError((caught as Error).message) });
  if (error && !start) return <ErrorBox message={error} />; if (!start) return <Loading />;
  const question = start.questions[index]; const minutes = left === null ? null : `${Math.floor(left / 60).toString().padStart(2, '0')}:${(left % 60).toString().padStart(2, '0')}`; const answered = Object.keys(answers).length;

  return <div className="mx-auto max-w-4xl">
    <header className="mb-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><DifficultyBadge value={start.test.difficulty} /><span className="text-xs font-semibold text-slate-400">{answered}/{start.questions.length} javob berildi</span></div><h1 className="mt-2 text-xl font-bold tracking-tight text-slate-950 sm:text-2xl">{start.test.title}</h1></div>{minutes && <div className={`flex items-center gap-2 self-start rounded-2xl px-4 py-2.5 font-mono text-lg font-bold sm:self-auto ${left! < 60 ? 'animate-pulse bg-rose-100 text-rose-700' : 'border border-slate-200 bg-white text-slate-800 shadow-sm'}`}><Icon name="clock" className="h-5 w-5" />{minutes}</div>}</div><div className="mt-5"><div className="mb-2 flex justify-between text-xs font-semibold text-slate-400"><span>Savol {index + 1} / {start.questions.length}</span><span>{Math.round(((index + 1) / start.questions.length) * 100)}%</span></div><ProgressBar value={((index + 1) / start.questions.length) * 100} /></div></header>
    {error && <div className="mb-4"><ErrorBox message={error} /></div>}
    <section className="card p-5 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-violet-100 font-bold text-violet-700">{index + 1}</span><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{question.points} ball</p><h2 className="mt-1.5 text-lg font-bold leading-7 text-slate-950 sm:text-xl">{question.text}</h2></div></div><div className="mt-7 grid gap-3">{question.options.map((option, optionIndex) => { const selected = answers[question.id] === option.id; return <label key={option.id} className={`group flex cursor-pointer items-center gap-4 rounded-2xl border p-4 transition sm:p-5 ${selected ? 'border-violet-500 bg-violet-50 shadow-[0_0_0_3px_rgba(139,92,246,.08)]' : 'border-slate-200 hover:border-violet-300 hover:bg-violet-50/40'}`}><input className="sr-only" type="radio" name={question.id} checked={selected} onChange={() => setAnswers(current => ({ ...current, [question.id]: option.id }))} /><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl text-sm font-bold transition ${selected ? 'bg-violet-600 text-white' : 'bg-slate-100 text-slate-500 group-hover:bg-violet-100 group-hover:text-violet-600'}`}>{String.fromCharCode(65 + optionIndex)}</span><span className={`text-sm leading-6 sm:text-base ${selected ? 'font-semibold text-violet-950' : 'text-slate-700'}`}>{option.text}</span>{selected && <Icon name="check" className="ml-auto h-5 w-5 shrink-0 text-violet-600" />}</label>; })}</div></section>
    <footer className="mt-5 flex items-center justify-between gap-3"><button className="btn-secondary" disabled={!index} onClick={() => setIndex(current => current - 1)}>Oldingi</button><div className="hidden gap-1.5 sm:flex">{start.questions.map((item, itemIndex) => <button key={item.id} onClick={() => setIndex(itemIndex)} aria-label={`${itemIndex + 1}-savol`} className={`h-2 rounded-full transition ${itemIndex === index ? 'w-6 bg-violet-600' : answers[item.id] ? 'w-2 bg-emerald-400' : 'w-2 bg-slate-200'}`} />)}</div>{index < start.questions.length - 1 ? <button className="btn-primary" onClick={() => setIndex(current => current + 1)}>Keyingi<Icon name="arrow" className="h-4 w-4" /></button> : <button className="btn-primary" disabled={submit.isPending} onClick={() => setConfirmOpen(true)}>{submit.isPending ? 'Hisoblanmoqda…' : <>Yakunlash<Icon name="check" className="h-4 w-4" /></>}</button>}</footer><ConfirmDialog open={confirmOpen} busy={submit.isPending} title="Testni yakunlaysizmi?" description={answered < start.questions.length ? `${start.questions.length} ta savolning ${answered} tasiga javob berdingiz. Javobsiz ${start.questions.length - answered} ta savol xato hisoblanadi.` : 'Barcha savollarga javob berdingiz. Yakunlagandan keyin javoblarni o‘zgartirib bo‘lmaydi.'} confirmLabel="Yakunlash" onConfirm={() => { setConfirmOpen(false); submit.mutate(); }} onCancel={() => setConfirmOpen(false)} />
  </div>;
}
