'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { Icon } from '../../../../../components/icons';
import { DifficultyBadge, ErrorBox, Loading, PageHeader, difficultyLabel } from '../../../../../components/ui';
import { api } from '../../../../../lib/api';
import { Difficulty, Test, Topic } from '../../../../../types';

type AdminTest = Omit<Test, 'questions'> & { questions: { id: string; text: string; order: number; points: number; options: { id: string; text: string; order: number; isCorrect: boolean }[] }[] };

export default function EditTestPage() {
  const { id } = useParams<{ id: string }>(); const queryClient = useQueryClient();
  const { data: test, isLoading, error } = useQuery({ queryKey: ['admin', 'test', id], queryFn: () => api<AdminTest>(`/admin/tests/${id}`) });
  const { data: topics = [] } = useQuery({ queryKey: ['admin', 'topics'], queryFn: () => api<Topic[]>('/admin/topics') });
  const [question, setQuestion] = useState({ text: '', order: '', points: '1', correct: '1', options: ['', '', '', ''] }); const [message, setMessage] = useState(''); const [messageType, setMessageType] = useState<'success'|'error'>('success');
  const notify = (text: string, type: 'success'|'error' = 'success') => { setMessage(text); setMessageType(type); };
  const add = useMutation({ mutationFn: () => api(`/admin/tests/${id}/questions`, { method: 'POST', body: JSON.stringify({ text: question.text, order: Number(question.order), points: Number(question.points), options: question.options.map((text, index) => ({ text, order: index + 1, isCorrect: String(index + 1) === question.correct })) }) }), onSuccess: () => { setQuestion({ text: '', order: '', points: '1', correct: '1', options: ['', '', '', ''] }); notify('Savol muvaffaqiyatli qo‘shildi.'); queryClient.invalidateQueries({ queryKey: ['admin', 'test', id] }); }, onError: caught => notify((caught as Error).message, 'error') });
  const remove = useMutation({ mutationFn: (questionId: string) => api(`/admin/questions/${questionId}`, { method: 'DELETE' }), onSuccess: () => { notify('Savol o‘chirildi.'); queryClient.invalidateQueries({ queryKey: ['admin', 'test', id] }); } });
  const update = useMutation({ mutationFn: (form: FormData) => api(`/admin/tests/${id}`, { method: 'PATCH', body: JSON.stringify({ title: form.get('title'), description: form.get('description'), topicId: form.get('topicId'), difficulty: form.get('difficulty'), durationMinutes: Number(form.get('durationMinutes')), isActive: form.get('isActive') === 'on' }) }), onSuccess: () => { notify('Test ma’lumotlari saqlandi.'); queryClient.invalidateQueries({ queryKey: ['admin', 'test', id] }); }, onError: caught => notify((caught as Error).message, 'error') });
  if (isLoading) return <Loading />; if (error || !test) return <ErrorBox message={error?.message ?? 'Test topilmadi'} />;
  const changeOption = (index: number, value: string) => setQuestion(current => ({ ...current, options: current.options.map((option, optionIndex) => optionIndex === index ? value : option) }));

  return <>
    <PageHeader eyebrow="Test muharriri" title={test.title} description={`${test.topic.name} mavzusi · ${test.questions.length} ta savol`} action={<Link href="/admin/tests" className="btn-secondary">Testlar ro‘yxati</Link>} />
    {message && <div className={`mb-5 flex items-center gap-2 rounded-2xl border p-4 text-sm font-semibold ${messageType === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-rose-200 bg-rose-50 text-rose-700'}`}><Icon name={messageType === 'success' ? 'check' : 'close'} className="h-5 w-5" />{message}</div>}
    <form className="card grid gap-5 sm:grid-cols-2" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); update.mutate(new FormData(event.currentTarget)); }}><div className="flex items-center gap-3 border-b border-slate-100 pb-5 sm:col-span-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-100 text-sky-600"><Icon name="tests" className="h-5 w-5" /></span><div><h2 className="font-bold">Asosiy ma’lumotlar</h2><p className="text-xs text-slate-400">Test sozlamalari va ko‘rinishi</p></div><div className="ml-auto"><DifficultyBadge value={test.difficulty} /></div></div><label className="label sm:col-span-2">Nomi<input className="input" name="title" defaultValue={test.title} required /></label><label className="label sm:col-span-2">Tavsif<textarea className="input" name="description" defaultValue={test.description} /></label><label className="label">Mavzu<select className="input" name="topicId" defaultValue={test.topic.id}>{topics.map(topic => <option value={topic.id} key={topic.id}>{topic.name}</option>)}</select></label><label className="label">Daraja<select className="input" name="difficulty" defaultValue={test.difficulty}>{(['EASY','MEDIUM','HARD'] as Difficulty[]).map(value => <option key={value} value={value}>{difficultyLabel[value]}</option>)}</select></label><label className="label">Davomiyligi (daq.)<input className="input" name="durationMinutes" type="number" min="1" defaultValue={test.durationMinutes ?? 20} /></label><label className="flex cursor-pointer items-center gap-3 self-end rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700"><input name="isActive" type="checkbox" className="h-4 w-4 accent-violet-600" defaultChecked={test.isActive} />Test faol</label><div className="sm:col-span-2"><button className="btn-primary" disabled={update.isPending}>{update.isPending ? 'Saqlanmoqda…' : <><Icon name="check" className="h-4 w-4" />O‘zgarishlarni saqlash</>}</button></div></form>

    <section className="mt-7 grid items-start gap-6 xl:grid-cols-[1fr_420px]"><div className="card"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><p className="eyebrow mb-1">Test tarkibi</p><h2 className="text-lg font-bold">Savollar <span className="text-slate-400">({test.questions.length})</span></h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-600"><Icon name="question" /></span></div><div className="mt-5 space-y-3">{[...test.questions].sort((a, b) => a.order - b.order).map(item => <article className="group rounded-2xl border border-slate-200 p-4 transition hover:border-violet-200 hover:bg-violet-50/20" key={item.id}><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-sm font-bold text-slate-600">{item.order}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-bold leading-6 text-slate-900">{item.text}</h3><button className="shrink-0 text-slate-300 transition hover:text-rose-600" onClick={() => { if (confirm('Savol o‘chirilsinmi?')) remove.mutate(item.id); }} aria-label="Savolni o‘chirish"><Icon name="close" className="h-5 w-5" /></button></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{[...item.options].sort((a, b) => a.order - b.order).map((option, optionIndex) => <p key={option.id} className={`flex items-center gap-2 rounded-lg px-2.5 py-2 text-xs ${option.isCorrect ? 'bg-emerald-50 font-semibold text-emerald-700' : 'bg-slate-50 text-slate-500'}`}><span className="font-bold">{String.fromCharCode(65 + optionIndex)}.</span><span className="truncate">{option.text}</span>{option.isCorrect && <Icon name="check" className="ml-auto h-3.5 w-3.5" />}</p>)}</div><p className="mt-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400">{item.points} ball</p></div></div></article>)}{!test.questions.length && <div className="py-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-600"><Icon name="question" /></span><h3 className="mt-3 font-bold">Savollar hali yo‘q</h3><p className="mt-1 text-sm text-slate-500">O‘ng tomondagi forma orqali birinchi savolni qo‘shing.</p></div>}</div></div>

      <form className="card xl:sticky xl:top-6" onSubmit={(event: FormEvent) => { event.preventDefault(); setMessage(''); add.mutate(); }}><div className="flex items-center gap-3 border-b border-slate-100 pb-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-600"><Icon name="plus" /></span><div><h2 className="font-bold">Yangi savol</h2><p className="text-xs text-slate-400">To‘g‘ri variantni belgilang</p></div></div><label className="label mt-5 block">Savol matni<textarea className="input" value={question.text} onChange={e => setQuestion(current => ({ ...current, text: e.target.value }))} placeholder="Savolni kiriting…" required /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="label">Tartib<input className="input" type="number" min="1" value={question.order} onChange={e => setQuestion(current => ({ ...current, order: e.target.value }))} required /></label><label className="label">Ball<input className="input" type="number" min="1" value={question.points} onChange={e => setQuestion(current => ({ ...current, points: e.target.value }))} required /></label></div><p className="mb-2 mt-5 text-xs font-bold uppercase tracking-wider text-slate-400">Javob variantlari</p><div className="space-y-2.5">{question.options.map((option, index) => <label className={`flex cursor-pointer items-center gap-2 rounded-xl border p-2 transition ${question.correct === String(index + 1) ? 'border-emerald-300 bg-emerald-50' : 'border-slate-200'}`} key={index}><input type="radio" name="correct" className="h-4 w-4 accent-emerald-600" checked={question.correct === String(index + 1)} onChange={() => setQuestion(current => ({ ...current, correct: String(index + 1) }))} /><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-white text-xs font-bold text-slate-500">{String.fromCharCode(65 + index)}</span><input className="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm outline-none placeholder:text-slate-400" placeholder={`${index + 1}-variant`} value={option} onChange={e => changeOption(index, e.target.value)} required />{question.correct === String(index + 1) && <Icon name="check" className="h-4 w-4 text-emerald-600" />}</label>)}</div><button className="btn-primary mt-6 w-full" disabled={add.isPending}>{add.isPending ? 'Qo‘shilmoqda…' : <><Icon name="plus" className="h-4 w-4" />Savolni qo‘shish</>}</button></form>
    </section>
  </>;
}
