import { Body, Controller, Delete, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger'; import { UserRole } from '../../common/types/database.enums'; import { Roles } from '../../common/decorators/roles.decorator'; import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard'; import { RolesGuard } from '../../common/guards/roles.guard'; import { AdminService } from './admin.service'; import { CreateQuestionDto, CreateTestDto, CreateTopicDto, TestAdminFilterDto, UpdateQuestionDto, UpdateTestDto, UpdateTopicDto, UpdateUserDto, UserFilterDto } from './dto/admin.dto';
@ApiTags('Admin') @ApiBearerAuth() @UseGuards(JwtAuthGuard, RolesGuard) @Roles(UserRole.ADMIN) @Controller('admin')
export class AdminController {
 constructor(private admin: AdminService) {}
 @Get() dashboard() { return this.admin.dashboard(); }
 @Get('users') users(@Query() q: UserFilterDto) { return this.admin.users(q); } @Get('users/:id') user(@Param('id') id: string) { return this.admin.user(id); } @Patch('users/:id') updateUser(@Param('id') id: string, @Body() dto: UpdateUserDto) { return this.admin.updateUser(id, dto); } @Delete('users/:id') deleteUser(@Param('id') id: string) { return this.admin.deleteUser(id); }
 @Get('topics') topics() { return this.admin.topics(); } @Post('topics') createTopic(@Body() dto: CreateTopicDto) { return this.admin.createTopic(dto); } @Get('topics/:id') topic(@Param('id') id: string) { return this.admin.topic(id); } @Patch('topics/:id') updateTopic(@Param('id') id: string, @Body() dto: UpdateTopicDto) { return this.admin.updateTopic(id, dto); } @Delete('topics/:id') deleteTopic(@Param('id') id: string) { return this.admin.deleteTopic(id); }
 @Get('tests') tests(@Query() q: TestAdminFilterDto) { return this.admin.tests(q); } @Post('tests') createTest(@Body() dto: CreateTestDto) { return this.admin.createTest(dto); } @Get('tests/:id') test(@Param('id') id: string) { return this.admin.test(id); } @Patch('tests/:id') updateTest(@Param('id') id: string, @Body() dto: UpdateTestDto) { return this.admin.updateTest(id, dto); } @Delete('tests/:id') deleteTest(@Param('id') id: string) { return this.admin.deleteTest(id); }
 @Post('tests/:testId/questions') createQuestion(@Param('testId') testId: string, @Body() dto: CreateQuestionDto) { return this.admin.createQuestion(testId, dto); } @Patch('questions/:id') updateQuestion(@Param('id') id: string, @Body() dto: UpdateQuestionDto) { return this.admin.updateQuestion(id, dto); } @Delete('questions/:id') deleteQuestion(@Param('id') id: string) { return this.admin.deleteQuestion(id); }
}
