'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FormEvent, useState } from 'react';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { Icon } from '../../../components/icons';
import { EmptyState, Loading, PageHeader } from '../../../components/ui';
import { api } from '../../../lib/api';
import { Topic } from '../../../types';

export default function TopicsPage() {
  const queryClient = useQueryClient(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState('');
  const { data, isLoading } = useQuery({ queryKey: ['admin', 'topics'], queryFn: () => api<Topic[]>('/admin/topics') });
  const create = useMutation({ mutationFn: () => api<Topic>('/admin/topics', { method: 'POST', body: JSON.stringify({ name, description }) }), onSuccess: () => { setName(''); setDescription(''); queryClient.invalidateQueries({ queryKey: ['admin', 'topics'] }); }, onError: caught => setError((caught as Error).message) });
  const [pending, setPending] = useState<{ id: string; name: string } | null>(null);
  const remove = useMutation({ mutationFn: (id: string) => api(`/admin/topics/${id}`, { method: 'DELETE' }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin', 'topics'] }) });
  if (isLoading) return <Loading />;

  return <><PageHeader eyebrow="Kontent tuzilmasi" title="Mavzular" description="Testlarni tartibli saqlash uchun fan va yo‘nalishlarni boshqaring." />
    <form className="card mb-6" onSubmit={(event: FormEvent) => { event.preventDefault(); setError(''); create.mutate(); }}><div className="mb-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-600"><Icon name="plus" /></span><div><h2 className="font-bold text-slate-900">Yangi mavzu</h2><p className="text-xs text-slate-400">Nomi aniq va qisqa bo‘lsin</p></div></div><div className="grid gap-3 md:grid-cols-[1fr_2fr_auto]"><label className="sr-only" htmlFor="topic-name">Mavzu nomi</label><input id="topic-name" className="input mt-0" placeholder="Masalan: Matematika" value={name} onChange={e => setName(e.target.value)} required /><label className="sr-only" htmlFor="topic-description">Tavsif</label><input id="topic-description" className="input mt-0" placeholder="Mavzu haqida qisqa tavsif" value={description} onChange={e => setDescription(e.target.value)} /><button className="btn-primary" disabled={create.isPending}><Icon name="plus" className="h-4 w-4" />{create.isPending ? 'Qo‘shilmoqda…' : 'Qo‘shish'}</button></div>{error && <p className="mt-3 text-sm font-medium text-rose-600">{error}</p>}</form>
    {!data?.length ? <EmptyState title="Mavzular mavjud emas" description="Birinchi mavzuni qo‘shing, so‘ng unga testlar biriktiring." icon="topics" /> : <><div className="grid gap-3 md:hidden">{data.map(topic => <article className="card p-4" key={topic.id}><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-600"><Icon name="topics" className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="font-bold">{topic.name}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{topic.description || 'Tavsif kiritilmagan'}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{topic._count?.tests ?? 0} test</span></div><button className="text-rose-500" onClick={() => setPending({ id: topic.id, name: topic.name })} aria-label="Mavzuni o‘chirish"><Icon name="close" className="h-5 w-5" /></button></div></article>)}</div>
    <div className="table-shell hidden overflow-x-auto md:block"><table className="data-table"><thead><tr><th>Nomi</th><th>Tavsif</th><th>Testlar</th><th /></tr></thead><tbody>{data.map(topic => <tr key={topic.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-100 text-amber-600"><Icon name="topics" className="h-4 w-4" /></span><b className="text-slate-900">{topic.name}</b></div></td><td>{topic.description || '—'}</td><td><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{topic._count?.tests ?? 0}</span></td><td className="text-right"><button className="btn-danger min-h-9 px-3 py-1.5" onClick={() => setPending({ id: topic.id, name: topic.name })}><Icon name="close" className="h-4 w-4" />O‘chirish</button></td></tr>)}</tbody></table></div></>}
  <ConfirmDialog open={!!pending} destructive title="Mavzuni o‘chirasizmi?" description={`“${pending?.name}” mavzusi va unga tegishli barcha testlar o‘chiriladi. Bu amalni qaytarib bo‘lmaydi.`} confirmLabel="O‘chirish" cancelLabel="Bekor qilish" busy={remove.isPending} busyLabel="O‘chirilmoqda…" error={remove.error?.message} onConfirm={() => remove.mutate(pending!.id, { onSuccess: () => setPending(null) })} onCancel={() => { remove.reset(); setPending(null); }} />
  </>;
}
